### ISSUE TITLE
Forward vs BackSlash

### ISSUE THREAD

**Issue by DougJod** [celador/ForceCode#20]
Some of the string parsing functions, such as: getName->getNameFromClassBody() and getName->getAuraNameFromFileName(), are using hard coded forward slashes to parse paths. This causes problems with Windows path names.

**Comment by mgarf** [comment]
#8 and #19 should resolve this.

**Comment by DougJod** [comment]
Have those ( #8 and #19 ) been merged into master? I'm still getting the error after installing from source.

**Comment by DougJod** [comment]
@mgarf Thanks. I think you are right that this issue #20 is covered by #8 and #19. We can probably close this one.

**Comment by mgarf** [comment]
@DougJod I believe getFileName was missed. I'll create a pull request now for that

**Comment by DougJod** [comment]
Closed as duplicate of #19
