### ISSUE TITLE
3.12.0 not showing save/build errors

### ISSUE THREAD

**Issue by frizz2310** [celador/ForceCode#236]
**Describe the bug**
Since updating to 3.12.0, I no longer see save/build errors in the notification area in the bottom right of vscode.  Have to watch closely for ClassName.apex (checkmark) to know if the file saved to Salesforce.

**To Reproduce**
1. Install 3.12.0
2. Save a file with syntax errors
3. Saving indicator ("ForceCode: Executing 1 Task(s)") shows and quickly goes away, but no error
4. **Change ForceCode version to 3.11.3 and it works as it should

**Expected behavior**
Should display a build error in the vscode notification center.

**Screenshots**
Expecting this:
![image](https://user-images.githubusercontent.com/23323591/52134297-e2500680-2608-11e9-8e84-acf84267440c.png)

**Desktop (please complete the following information):**
 - OS: MacOS 10.14.1 and 10.14.2
           Windows 10
 - VSCode version 1.30.2
 - ForceCode Version 3.12.3

**Comment by daishi4u** [comment]
Errors are now only shown in the problems area of vscode

**Comment by RandallFlagg** [comment]
@daishi4u Can the problem area be opened automatically in case of an error(s)?

**Comment by frizz2310** [comment]
I'm not seeing any problems generated for build errors either.  There is no indication that the build failed.

**Comment by daishi4u** [comment]
@frizz2310 what are you trying to save when there are now problems generated?

**Comment by frizz2310** [comment]
Sorry guess that would help...
Lightning components and their css files are the only two I've found so far.  To repeat, open a .cmp file, add <style> tags or an unclosed tag or anything to cause syntax error and save.  Same with CSS.  Others are generating errors - js controllers and helpers, apex classes, vf pages, etc.

**Comment by daishi4u** [comment]
This is fixed in 3.13.0

**Comment by frizz2310** [comment]
Still seeing the same issue with component controller js files.  I tried to save with an eslint error and there was no notification, no error generated, and no save.

ForceCode 3.13.0
VScode 1.31.0

**Comment by daishi4u** [comment]
@frizz2310 yes I did notice that too and put a fix in place for the 3.13.1 release. If you are on slack you can test the upcoming release by joining the beta-testing channel
