### ISSUE TITLE
Cannot deploy .js-meta.xml file of LWC

### ISSUE THREAD

**Issue by Radon7** [celador/ForceCode#249]
**Describe the bug**
When I try to save the .js-meta.xml file of LWC the changes are not deployed to the org

**To Reproduce**
1. Create a LWC
2. modify the meta file (ie change isExposed tag to true and add targets
3. save the file. ForceCode tries to push the file and say it succeded
4. retrieve the LWC from the org. The changes are not saved

**Expected behavior**
The .js-meta.xml file should be saved along the other ones

**Desktop (please complete the following information):**
 - OS: Mac OSX HighSierra
 - VSCode version 1.31.1
 - ForceCode Version 3.14.1

**UPDATE**
It seems that the extension doesn't check if the code inside the js file has errors and deploys it anyway showing no error

**Comment by daishi4u** [comment]
What kind of error did your file have in it that it didn't report back to you? I just tried saving with errors and it reported that I had an error in the file. Otherwise it saves just fine

**Comment by Radon7** [comment]
![recording](https://user-images.githubusercontent.com/11978693/53043411-b2b65080-3488-11e9-9d29-5325f1ffef9e.gif)
I'll leave a gif of what I've tried to do. It seems strange. No console error or anything even toggling the developer tools

For the error in JS was my fault. It works just fine

**Comment by daishi4u** [comment]
This is fixed in 3.15.1

**Comment by jonathanwiesel** [comment]
I'm still experiencing this in 3.15.2. 
In fact, creating a new project and retrieving LWCs that have `isExposed = true` and `targetConfigs`
doesn't appear so when retrieved, they appear as `isExposed = false` and without `targetConfigs`.

Can you confirm?

**Comment by daishi4u** [comment]
I can not confirm this, as I just tested and was able to retrieve with all properties. Although, I tested with the newest beta release 3.16.0-4 and there are deployment fixes so maybe it never got saved with those properties in the first place?
